baseURL = "/"
languageCode = "en-us"
title = "Steven Wade"
theme = "ink"
paginate = 5

copyright = "© Steven Wade"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

googleAnalytics = "UA-30720951-1"
disqusShortname = "stevenwadejr"

[params]
	subtitle = "Husband, Father, Software Engineer (in that order)"

	excerptLength = 200

	# Optional 64x64 avatar image.
	avatar = "/images/profile-pic.jpeg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	#excludedTypes

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
#[[menu.main]]
#name = "Home"
#url = "/"
#weight = 1


[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/stevenwadejr"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/stevenwadejr"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
	tag = "tags"

[permalinks]
	post = "/:year/:month/:day/:title/"